services:
  - type: web
    name: apex-tracker-backend
    env: node
    region: singapore
    plan: free
    rootDir: .
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: DATABASE_URL
        sync: false          # Set this in Render dashboard → paste your Render DB connection string
      - key: JWT_SECRET
        sync: false          # Set this in Render dashboard → any long random string
      - key: FRONTEND_URL
        sync: false          # Set this in Render dashboard → your Vercel URL e.g. https://apex-tracker.vercel.app
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: GOOGLE_CLIENT_ID
        value: 708631090264-c0fchbcjcbphkngbqf5vn1qmekrrpfo9.apps.googleusercontent.com
